image: node:12.12.0

stages:
  - deps 
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: deps
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

build:
  stage: build
  script:
    - npm run build

test:
  stage: test
  script:
    - npm run test-ci --ci --detectOpenHandles --forceExit

test:eslint:
  stage: test
  script:
    - npm run eslint

pages:
  stage: deploy
  image: node:12.12.0
  script:
    - npm run build-storybook
    - mv .storybook-build public
  cache:
    paths:
      - node_modules/
    policy: pull
  artifacts:
    paths:
      - public
  #  only:
  #    - master
  allow_failure: true
